site:
  name: Bandageman Studios
  tagline: Super-serious game development
  location: Saint Louis, Missouri
  base_url: https://bandageman.com
homepage:
  title: Bandageman Studios - Super-serious game development
  description: Bandageman Studios - Super-serious indie game development from Saint
    Louis, Missouri. Play our PICO-8 games!
  keywords: indie games, PICO-8, retro games, pixel art games, bandageman studios
  og_image: https://bandageman.com/images/bandageman-logo.png
  coming_soon_slots: 1
games:
- slug: space-cowboy
  title: Space Cowboy
  description: Play Space Cowboy, a PICO-8 game by Bandageman Studios
  keywords: Space Cowboy, PICO-8, indie game, retro game, bandageman studios
- slug: dans-dream-run
  title: Dan's Dream Run
  description: Play Dan's Dream Run, a PICO-8 game by Bandageman Studios
  keywords: Dan's Dream Run, PICO-8, indie game, retro game, bandageman studios
- slug: dream-ghoul
  title: Dream Ghoul
  description: Play Dream Ghoul, a PICO-8 game by Bandageman Studios
  keywords: Dream Ghoul, PICO-8, indie game, retro game, bandageman studios
